onezerokang/algorithm-study-jungle

강원영/class02/1018.py

(구현에 오류가 있어 다른 사람의 코드를 참조하여 풀었습니다
일주일 뒤에 다시 풀어본 후 코드 업데이트를 할 예정입니다)

2023-05-15 코드 제출

---

강원영/class02/10845.py

파이썬으로 큐를 구현했습니다.
pop 명령의 경우 시간복잡도가 O(n)이라 아쉽지만
시간 내에 제출해야 해서 그냥 간단하게 처리했습니다.

2023-05-16 제출 : 큐

---

표혜민/README.md
표혜민/class02/10845/1.ts

[2023.05.16][10845번]ts 문제 풀이 완료

---

박주영/class02/10866.py

first commit

---

강원영/class02/10866.py

2023-05-17 제출

---

강원영/class02/10816.py

저는 딕셔너리에 카드 수를 저장하는 방식으로 풀었습니다.
아래는 처음 제출한 틀린 코드인데, `count_cards`의 원소가 중복으로 들어올 수 있다는 것을 고려하지 못했습니다.
```py
import sys
input = sys.stdin.readline
N = int(input())
cards = list(map(int, input().split()))
M = int(input())
count_cards = (list(map(int, input().split()))) # 이 카드가 중복으로 들어올 수 있다는 것을 고려하지 못했음.
answer = {}
for card in count_cards:
answer[card] = 0
for card in cards:
if card in answer:
answer[card] += 1
print(" ".join(map(str, answer.values())))
```
이후에는 answer 딕셔너리의 값을 바로 출력하는 것이 아닌 count_cards를 순회하면서 출력하도록 변경하였습니다
```py
import sys
input = sys.stdin.readline
N = int(input())
cards = list(map(int, input().split()))
M = int(input())
count_cards = (list(map(int, input().split())))
answer = {}
for card in count_cards:
answer[card] = 0
for card in cards:
if card in answer:
answer[card] …
```

2023-05-18 숫자 카드2

---

README.md
표혜민/class02/10816/1.ts

updated solved status in README.md

---

강원영/class02/2798.py

combinations 패키지로 풀었습니다.
오늘 내에 순열과 조합을 직접 구현해보려고 합니다.

2023-05-20 2798.py

---

표혜민/README.md
표혜민/class02/WEEK02/11050/0.py

* 파이썬 풀이 완료
* itertools없이 조합 구현해보도록 해보겠습니다.

2023.05.23 | 11050 | 이항계수 | Pyotato : py 풀이 완료

---

README.md
표혜민/README.md
표혜민/class03/WEEK03/11399/0.py
표혜민/class03/WEEK03/11399/1.ts

2023.05.24 | 11399 | ATM | pyotato : py & ts solved

---

장재균/class02/11399/0.py
장재균/class02/2839/0.py

Jang jae kyun

---

강원영/class03/1012.py
강원영/class03/1463.py

그래프에서 1로 연결된 노드 덩어리의 개수를 세는 문제입니다.
문제 해결 알고리즘은 다음과 같습니다.
1. for loop으로 노드를 방문하면서 노드가 1인지 검사
2. 노드가 1일 경우 bfs 함수를 호출하고 결과에 1을 더해줌
3. bfs 함수는 값이 1인 노드를 탐색하면서 값을 1에서 0으로 수정함.
참고: 저번에 못풀었던 1로 만들기 문제도 풀었습니다.

1012.py and 1463.py

---

README.md
표혜민/README.md
표혜민/class03/WEEK04/1012/0.py

문제를잘못 읽어서 입력값 받아오는데에 이슈가 있느라 
시간 내에는 못풀었습니다 ㅜㅜ

1021 solved, updated README

---

표혜민/class03/WEEK04/1003/0.py

처음에는 피보나치니까 재귀로 접근할까 했는데 규칙이 있는 느낌이라 dp로 풀었습니다.

2023.05.31 | 1003 | pyotato

---

장재균/class02/7662/0.py

7662 이중 우선순위 큐

---

박주영/class02/9375.py
박주영/class03/11659.py
박주영/class03/14940.py

- (2023.06.05) 14940 쉬운 최단 거리
- (2023.06.06) 11659 구간 합 구하기 4

쉬운 최단거리/bfs, 구간 합 구하기 4/누적합

---

장재균/class02/1149/0.py

마지막에 조금 참고했는데, 생각보다 쉬워서 조금 더 생각해볼걸 그랬어여ㅠㅠㅠㅠㅠ

1149 RGB거리

---

강원영/class03/1149.py
강원영/class03/1927.py

처음에는 재귀 함수를 이용해서 브루트포스로 풀었습니다. 하지만 시간초과가 발생하여 하향식으로 풀어보려고 했는데 잘 안되더군요.
그래서 상향식으로 풀었습니다.
나중에 하향식으로 풀 수 있는 방법을 생각해봐야 할 것 같습니다.
핵심 로직은 homes를 거꾸로 순회하면서 homes[i][j]의 값을 homes[i][j]를 선택했을 때 얻을 수 있는 최소 값으로 변경해줬습니다.

Onezerokang

---

README.md
표혜민/README.md
표혜민/class04/WEEK05/1932/0.py

밑의 자식 가지들의 함 중 가장 큰 거를 넣어 저장해서 푸는 dp문제풀이

1932 풀이 완료

---

장재균/class02/1918/0.py

예전에 비슷한 문제 풀어본거같아서 기억 살리면서 하다가 결국은 참고했슴다! ㅜ

1918 후위 표기식

---

README.md
표혜민/README.md
표혜민/class04/WEEK07/15654/0.py

순열로 풀이했는데
백트래킹 문제로 분류되어 있더라구요.
한번 백트래킹으로도 풀이하겠습니다.

15654 풀이 완료

---

README.md
표혜민/README.md
표혜민/class04/WEEK07/15663/0.py

15663 풀이 완료. permutation과 set으로 풀이했습니다.

15663 풀이 완료

---

README.md
표혜민/README.md
표혜민/class04/WEEK07/14888/0.py
표혜민/class04/WEEK07/15663/0.py

1753은 저번에 혼자 다익스트라 공부를 위해 풀어서 아래에 풀이 첨부합니다. 
```python
from sys import stdin,maxsize
from heapq import heappush, heappop
V,E = map(int, stdin.readline().strip().split())
inf = maxsize
S = int(stdin.readline().strip())
dp = [inf]*(V+1) #방문여부
heap = []
g = [[] for _ in range(V+1)]
def dijkstra(s):
for _ in range(E): #노드 그래프 초기화
u,v,w = map(int,stdin.readline().strip().split())
g[u].append((w,v)) #가중치, 목적지 노드
dp[s]=0 #시작점은 0으로
heappush(heap,(0,s)) #시작점 heap넣기
while heap:
c,n = heappop(heap)
if dp[n] < c: #가중치 크면 업데이트 x
continue
for acc_w , nxt in g[n]:
nxt_w = acc_w + c
if nxt_w < dp[nxt]:
dp[nxt] = nxt_w
heappush(heap , (nxt_w , nxt))
for i in range(1,V+1):
print("INF") if dp[i]==inf else print(dp[i])
dijkstra(S)
```

readme update

---

박주영/class04/1238.py
박주영/class04/1865.py

1. **1865. 웜홀**은 벨만 포드 알고리즘은 음수의 가중치를 가지는 간선을 가지는 최소 비용 산출 문제입니다.
다익스트라 알고리즘과 비교하면 시간 복잡도가 O(VE)로 비효율적이긴 하지만 음수 가중치를 가진 특수한 상황에서 사용할 수 있습니다.
2. **1238. 파티**는 다익스트라 알고리즘을 활용해서 오가는 거리의 최대값을 구하는 문제입니다.
1  최단거리가 아니기 때문에
- 출발 지점에서 해당 지점까지 이동하는 최단거리를 모두 구하고
- 오가는 길을 모두 더해야 합니다.
- 시간 복잡도에서 이득을 취하기위해 파이썬의 heapq를 사용했고요.
- 기본적으로 heapq에 리스트가 주어지면 리스트의 첫번째 요소로 정렬이 되는 점을 주의해야 합니다.
- 첫번째 인덱스(인덱스 0)은 사용하지 않고요.
2 알고리즘 흐름
- Dijkstra함수에서는 해당 지점까지의 거리를 저장하는 distance 리스트를 만들어 heapq에 시작지점에서 접근 가능한 지점과 거리를 push합니다.
- heapq에서 현재 위치에서 갈수 있는 곳들을 하나씩 뽑아서 그 지점distance값과 비교하여 최소값을 distance로 대체합니다.
- 완성된 distance를 반환합니다.
- 함수에서 반환된 list를 사용해서 ans list를 만듭니다(만든 다익스트라 함수는 start지점에서 지점 i까지의 최단거리를 모두 구해 리스트에 저장하므로): 첫번째 리스트-> 시작점i, 도착점X(목적지), 두번째 리스트->시작점X,  도착점i로 구한 두 리스트를 더하여 해답을 구합니다.
- 여기에서 최대로 시간이 걸리는 녀석을 출력해 줍니다.

웜홀/벨만포드, 파티/다익스트라

---

README.md
표혜민/README.md
표혜민/class04/WEEK06/13549/0.py
표혜민/class04/WEEK06/1753/0.py
표혜민/class04/WEEK06/1753/minHeap.js
표혜민/class04/WEEK07/1238/0.py
표혜민/class04/WEEK07/1865/0.py

다익스트라 문제입니다.
정형화된 다익스트라 문제풀이는 시작점들에서 목표 지점까지 최단 거리를 구하는 경우가 대부분이며, 
이에 따라서 방문여부를 체크하면서 최단 경로일 경우만 업데이트를 해줘서 최단 거리를 구하는 방식이었습니다.
하지만 해당 문제는 목표지점을 방문하고, 돌아오는 길에도 최단 거리를 구해줘야하는 문제이므로, 
`파티 가는 길`과 `파티에서 돌아오는 길`의 최단 거리를 각각 구해서
이 둘을 합한 것의 최대값을 구해서 가장 오래 걸리는 학생의 소요 시간을 구했습니다.
while을 두번 써야한다는 점과 코드 반복이 된다는 점에서 리펙토링을 진행할 수 있을 거 같은데, 조언 부탁드립니다.

1238 풀이 완료

---

표혜민/README.md
표혜민/class04/WEEK07/11444/0.py
표혜민/class04/WEEK07/1238/1.py

해당 문제는 피보나치 수열의 특성을 이용한 문제입니다.
단순히 재귀를 활용해서 풀다가 recursion error 가 나서 recursion limit을 설정해줘서 풀이를 하려고 했지만, 해당 문제는 N의 크기가 터무니 없이 큰 수이기 때문에 접근법을 달리 해야하는 문제입니다. 
오늘 문제는 다른 풀이를 참고해서 풀었지만, 피보나치를 활용한 문제들을 여럿 풀어보고, 제곱근의 성질을 학습하여 다음에는 자력으로 풀어보고자합니다.
[ 피보나치 문제풀이들 참고 ](https://www.acmicpc.net/blog/view/28)
* 접근법 : 
* [[1,1],[1,0]]의 n-2승 값을 먼저 구해주자
* 초기값 1,1과 행렬의 곱해준다.
* 행렬의 곱셈 시 : `모듈러 연산은 곱셈,덧셈,뺄셈`에 대해서 `분배법칙이 성립`
* 덧셈한 걸 나눈 값으로 넣어주기
---
@dearmysolitude 님이 코드리뷰해주신 조언을 참고하여 리펙토링 진행했습니다. 😊
[👉코드리뷰 ](https://github.com/onezerokang/algorithm-study-jungle/pull/132) 와 [이전 풀이 ](https://github.com/onezerokang/algorithm-study-jungle/pull/132/files#diff-c0aa2dda43326166373dd0ff9de81e7d31123eae5e583750aa6e7b4dfd353050R1) 보러가기
[👉백준에서 보기](https://www.acmicpc.net/source/62460959)

11444 풀이, 1238 (파티) refactoring 완료 @dearmysolitude

---

장재균/class02/11444/o.py

와... 골드 넘어오니 문제 너무 어렵내요 ㅠㅠ
참고해서 풀었습니다

11444 피보나치 수6

---

장재균/class02/1167/0.py

원래 그래프탐색 문제를 좀 힘들어하긴 했는데 골드 문제니까 더 어렵내요ㅠㅠㅠㅠㅠ
참고해서 풀고 계속 코드를 봐야할거같아요

1167 트리의 지름

---

장재균/class02/1967/0.py

어제 문제와 비슷해서 어느정도 풀기는했지만 마지막에 참고해서 풀었습니다ㅠㅠㅠㅠㅠ

1967 트리의 지름

---

README.md
표혜민/README.md
표혜민/class04/WEEK07/1967/0.py
표혜민/class04/WEEK07/1967/1.ts

그제 풀었던 트리의 지름 문제와 비슷한 문제입니다. 
저번처럼 접근했는데 아직 풀이에 익숙하지 않아서 결국 정답을 참고했습니다. 
트리 관련 개념 & 문제 유형 공부를 더 해봐야겠습니다.

1967 풀이 : python & ts 풀이 완료
